---
- name: Restart loki
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: loki
    state: restarted
  when: ('loki' in loki_bins)

- name: Reload loki
  become: true
  ansible.builtin.systemd:
    name: loki
    state: reloaded
  when: ('loki' in loki_bins)

- name: Restart promtail
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: promtail
    state: restarted
  when: ('promtail' in loki_bins)

- name: Reload promtail
  become: true
  ansible.builtin.systemd:
    name: promtail
    state: reloaded
  when: ('promtail' in loki_bins)
